import Heading from "../components/Heading";
import QAComponent, { QAProps } from "../components/Q&A";

const questions: QAProps[] = [
    {
        question: "What is the OPINEX?",
        answer:"OpinionX is a opinion trading platorm. You will have AI-generated trending opinion polls to place your bets."
    },
    {
        question: "What is AI generated Opinion Polls?",
        answer: "We're leveraging the Google Trending News and processing it with the LLM Models to generate the opinion polls. There'll be no custom polls generated by users."
    },
    {
        question: "How can I start trading my opinions ?",
        answer: "You have to connect your web3 wallet and place the bet on the opinion of your choice"
    },
    {
        question: "Can I trade from you Website?",
        answer:"Yes, head over to the /app page"
    },
    {
        question: "What is the Service fee?",
        answer:"There is no Service fee! Enjoy trading your opinions. We would love you to serve you more :)"
    },
    {
        question: "How is the winner getting decided?",
        answer: "There is nothing like winner or loser here, this platform offers you to put your stake into the pool and sell the moment you feel your trade awarded you well.",
    },
];

export default function FAQSection() {
    return (
        <section className="w-full col gap-4">
            <Heading
                className="text-center"
                heading="FAQs"
                subHeading="Frequently asked Questions"
            />

            <div className="grid grid-cols-1 md:grid-cols-2 place-items-start mt-6">
                {questions.map((prop, i) => (
                    <QAComponent key={i} {...prop} />
                ))}
            </div>
        </section>
    );
}
